name: Build & Deploy to Cloud Run

on:
  push:
    branches: [main]

env:
  TF_VAR_project_id: ${{ vars.GCP_PROJECT_ID }}
  TF_VAR_region: ${{ vars.REGION }}
  TF_VAR_image_url: ${{ vars.IMAGE_URL }}
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Authenticate with GCP
      run: |
        echo "${GOOGLE_CREDENTIALS}" > $HOME/gcp-key.json
        gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
        gcloud config set project $TF_VAR_project_id
        gcloud auth configure-docker ${TF_VAR_region}-docker.pkg.dev

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.TF_VAR_image_url }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Use only app module (rename main-app.tf → main.tf)
      run: |
        cp terraform/main-app.tf terraform/main.tf
      working-directory: terraform/

    - name: Terraform Init
      run: terraform init
      working-directory: terraform/

    - name: Terraform Format Check
      run: terraform fmt -check
      working-directory: terraform/

    - name: Terraform Validate
      run: terraform validate
      working-directory: terraform/

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: terraform/

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: terraform/
