name: Setup Artifact Registry

on:
  workflow_dispatch:

env:
  TF_VAR_project_id: ${{ vars.GCP_PROJECT_ID }}
  TF_VAR_region: ${{ vars.REGION }}
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  setup-artifact-registry:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Authenticate with Google Cloud
      run: |
        echo "${GOOGLE_CREDENTIALS}" > $HOME/gcp-key.json
        gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
        gcloud config set project ${TF_VAR_project_id}

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Apply Artifact Registry Only
      run: terraform apply -auto-approve -target=google_artifact_registry_repository.repo
      working-directory: terraform
