name: Setup GCP Infrastructure

on:
  workflow_dispatch:  # Manual trigger only

env:
  TF_VAR_project_id: ${{ vars.GCP_PROJECT_ID }}
  TF_VAR_region: ${{ vars.REGION }}
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  setup-infra:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Authenticate with GCP
      run: |
        echo "${GOOGLE_CREDENTIALS}" > $HOME/gcp-key.json
        gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
        gcloud config set project $TF_VAR_project_id

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
      working-directory: terraform/infra

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform/infra
